---
 - name: Update apt-get repo and cache
   apt: update_cache=yes force_apt_get=yes 

 - name: "install packages"
   apt:
     name: "{{ item }}"
     state: present
   with_items:
    - wget
    - git
    - net-tools
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

 - name: Add Docker GPG apt Key
   apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

 - name: Add Docker Repository
   apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu bionic stable
     state: present

 - name: Update apt-get repo and cache
   apt: update_cache=yes force_apt_get=yes 

 - name: "install docker"
   apt:
     name: "{{ item }}"
     state: present
   with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
   